
line-length = 119

[lint]
# see https://docs.astral.sh/ruff/rules/ for meaning of rules
select = ["D", "E", "F", "NPY", "PD", "C4", "I"]

ignore = ["D1", "D202", "D205", "D400", "D404", "E501", "PD002", "PD901"]

# Apply isort rules, but not others like removing unused imports.
fixable = ["I"]


[lint.pydocstyle]
convention = "numpy"

[lint.per-file-ignores]
# Ignore unused imports in init
"__init__.py" = ["F401", "I001", "C0413"]